# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_fit_lrps <- function(Sigma, A, S, L, U, Zeros, l1, l2, mu, max_iter, rel_tol, abs_tol, print_every, has_zeros) {
    .Call('_lrpsadmm_rcppeigen_fit_lrps', PACKAGE = 'lrpsadmm', Sigma, A, S, L, U, Zeros, l1, l2, mu, max_iter, rel_tol, abs_tol, print_every, has_zeros)
}

